<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mime-info [
  <!ELEMENT mime-info (mime-type)+>
  <!ATTLIST mime-info xmlns CDATA #FIXED "http://www.freedesktop.org/standards/shared-mime-info">

  <!ELEMENT mime-type (comment|glob|magic|root-XML|alias|sub-class-of)*>
  <!ATTLIST mime-type type CDATA #REQUIRED>

  <!ELEMENT comment (#PCDATA)>
  <!ATTLIST comment xml:lang CDATA #IMPLIED>

  <!ELEMENT glob EMPTY>
  <!ATTLIST glob pattern CDATA #REQUIRED>

  <!ELEMENT magic (match)+>
  <!ATTLIST magic priority CDATA #IMPLIED>

  <!ELEMENT match (match)*>
  <!ATTLIST match offset CDATA #REQUIRED>
  <!ATTLIST match type (string|big16|big32|little16|little32|host16|host32|byte) #REQUIRED>
  <!ATTLIST match value CDATA #REQUIRED>
  <!ATTLIST match mask CDATA #IMPLIED>

  <!ELEMENT root-XML EMPTY>
  <!ATTLIST root-XML
  	namespaceURI CDATA #REQUIRED
	localName CDATA #REQUIRED>

  <!ELEMENT alias EMPTY>
  <!ATTLIST alias
  	type CDATA #REQUIRED>

  <!ELEMENT sub-class-of EMPTY>
  <!ATTLIST sub-class-of
  	type CDATA #REQUIRED>
]>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="application/andrew-inset">
    <comment>Andrew Toolkit inset</comment>
    <comment xml:lang="az">Andrew Toolkit sənədi</comment>
    <comment xml:lang="bg">Сбор от Andrew Toolkit</comment>
    <comment xml:lang="cs">Andrew Toolkit inset</comment>
    <comment xml:lang="cy">Mewnosodiad Andrew Toolkit</comment>
    <comment xml:lang="da">Andrew Toolkit indsæt</comment>
    <comment xml:lang="de">Andrew Toolkit-Inset</comment>
    <comment xml:lang="el">ενθεμα Εργαλειοσειράς Andrew</comment>
    <comment xml:lang="eo">ongleto de Andrew Toolkit</comment>
    <comment xml:lang="es">Inset del Andrew Toolkit</comment>
    <comment xml:lang="eu">Andrew Toolkit-eko elementua</comment>
    <comment xml:lang="fi">Andrew Toolkit -osio</comment>
    <comment xml:lang="fr">ajout Andrew Toolkit</comment>
    <comment xml:lang="hu">Andrew Toolkit-inset</comment>
    <comment xml:lang="it">Inset Andrew Toolkit</comment>
    <comment xml:lang="ja">Andrew ツールキットインセット</comment>
    <comment xml:lang="ko">Andrew 툴킷 inset</comment>
    <comment xml:lang="ms">Inset Andrew Toolkit</comment>
    <comment xml:lang="nb">Andrew verktøysett insett</comment>
    <comment xml:lang="nl">Andrew Toolkit-invoegsel</comment>
    <comment xml:lang="nn">Andrew Toolkit innsats</comment>
    <comment xml:lang="no">Andrew verktøysett insett</comment>
    <comment xml:lang="pl">Pakiet narzędziowy Andrew</comment>
    <comment xml:lang="pt">'inset' do Andrew Toolkit</comment>
    <comment xml:lang="pt_BR">Inset do Andrew Toolkit</comment>
    <comment xml:lang="sq">Inset Andrew Toolkit</comment>
    <comment xml:lang="sr">Andrew додатаг групе алата</comment>
    <comment xml:lang="sv">Andrew-verktygssamling insatt</comment>
    <comment xml:lang="uk">вкладка Andrew Toolkit</comment>
    <comment xml:lang="zh_TW">Andrew Toolkit 元件檔</comment>
    <glob pattern="*.ez"/>
  </mime-type>
  <mime-type type="application/illustrator">
    <comment>Adobe Illustrator document</comment>
    <comment xml:lang="bg">Документ, формат Adobe Illustrator</comment>
    <comment xml:lang="cs">Dokument Adobe Illustrator</comment>
    <comment xml:lang="da">Adobe Illustrator-dokument</comment>
    <comment xml:lang="de">Adobe Illustrator-Dokument</comment>
    <comment xml:lang="el">έγγραφο Adobe Illustrator</comment>
    <comment xml:lang="eo">dokumento de Adobe Illustrator</comment>
    <comment xml:lang="es">Documento de Adobe Illustrator</comment>
    <comment xml:lang="eu">Adobe Illustrator dokumentua</comment>
    <comment xml:lang="fi">Adobe Illustrator -asiakirja</comment>
    <comment xml:lang="fr">document Adobe Illustrator</comment>
    <comment xml:lang="hu">Adobe Illustrator-dokumentum</comment>
    <comment xml:lang="it">Documento Adobe Illustrator</comment>
    <comment xml:lang="ja">Adobe Illustrator ドキュメント</comment>
    <comment xml:lang="ko">Adobe Illustrator 문서</comment>
    <comment xml:lang="ms">Dokumen Adobe Illustrator</comment>
    <comment xml:lang="nb">Adobe Illustrator-dokument</comment>
    <comment xml:lang="nl">Adobe Illustrator-document</comment>
    <comment xml:lang="nn">Adobe Illustrator-dokument</comment>
    <comment xml:lang="no">Adobe Illustrator-dokument</comment>
    <comment xml:lang="pl">Dokument Adobe Illustratora</comment>
    <comment xml:lang="pt">documento Adobe Illustrator</comment>
    <comment xml:lang="pt_BR">Documento do Adobe Illustrator</comment>
    <comment xml:lang="ru">документ Adobe Illustrator</comment>
    <comment xml:lang="sq">Dokument Adobe Illustrator</comment>
    <comment xml:lang="sr">Адоуби Илустратор документ</comment>
    <comment xml:lang="sv">Adobe Illustrator-dokument</comment>
    <comment xml:lang="uk">Документ Adobe Illustrator</comment>
    <comment xml:lang="zh_CN">Adobe Illustrator 文档</comment>
    <comment xml:lang="zh_TW">Adobe Illustrator 文件</comment>
    <glob pattern="*.ai"/>
  </mime-type>
  <mime-type type="application/mac-binhex40">
    <comment>Macintosh BinHex-encoded file</comment>
    <comment xml:lang="az">Macintosh BinHex-kodlanmış fayl</comment>
    <comment xml:lang="bg">Файл, кодиран във формат BinHex за Macintosh</comment>
    <comment xml:lang="cs">Soubor kódovaný Macintosh BinHex</comment>
    <comment xml:lang="cy">Ffeil BinHex-amgodwyd Macintosh</comment>
    <comment xml:lang="da">Macintosh BinHex-kodet fil</comment>
    <comment xml:lang="de">Macintosh-Datei (BinHex-kodiert)</comment>
    <comment xml:lang="el">αρχείο Macintosh κωδικοποίησης BinHex</comment>
    <comment xml:lang="eo">dosiero kodigita laŭ Macintosh BinHex</comment>
    <comment xml:lang="es">Fichero Macintosh codificado con BinHex</comment>
    <comment xml:lang="eu">Macintosh BinHex-ekin kodetutako fitxategia</comment>
    <comment xml:lang="fi">Macintosh BinHex -koodattu tiedosto</comment>
    <comment xml:lang="fr">fichier encode Macintosh BinHex</comment>
    <comment xml:lang="hu">Macintosh BinHex kódolású fájl</comment>
    <comment xml:lang="it">File Macintosh codificato BinHex</comment>
    <comment xml:lang="ja">Macintosh BinHex エンコードファイル</comment>
    <comment xml:lang="ko">맥킨토시 BinHex-encoded 압축파일</comment>
    <comment xml:lang="ms">Fail terenkod-BinHex Macintosh</comment>
    <comment xml:lang="nb">Macintosh BinHe-kodet arkiv</comment>
    <comment xml:lang="nl">Macintosh BinHex-gecodeerd bestand</comment>
    <comment xml:lang="nn">Macintosh BinHex-koda fil</comment>
    <comment xml:lang="no">Macintosh BinHe-kodet arkiv</comment>
    <comment xml:lang="pl">Zakodowany w BinHex plik Macintosha</comment>
    <comment xml:lang="pt">ficheiro codificado em BinHex de Macintosh</comment>
    <comment xml:lang="pt_BR">Arquivo Macintosh codificado com BinHex</comment>
    <comment xml:lang="sq">File Macintosh i kodifikuar BinHex</comment>
    <comment xml:lang="sr">Мекинтош BinHex-encoded датотека</comment>
    <comment xml:lang="sv">Macintosh BinHex-kodad fil</comment>
    <comment xml:lang="uk">Файл закодований Macintosh BinHex</comment>
    <comment xml:lang="zh_CN">Macintosh BinHex 编码的文件</comment>
    <comment xml:lang="zh_TW">Macintosh BinHex 編碼檔</comment>
    <magic priority="50">
      <match value="must be converted with BinHex" type="string" offset="11"/>
    </magic>
  </mime-type>
  <mime-type type="application/mathematica">
    <comment xml:lang="en">Mathematica Notebook</comment>
    <glob pattern="*.nb"/>
    <magic priority="50">
      <match value="(************** Content-type: application/mathematica" type="string" offset="0"/>
      <match value="This notebook can be used on any computer system with Mathematica" type="string" offset="100:256"/>
      <match value="This is a Mathematica Notebook file.  It contains ASCII text" type="string" offset="10:256"/>
    </magic>
  </mime-type>
  <mime-type type="application/octet-stream">
    <comment>unknown</comment>
    <comment xml:lang="bg">Неизвестен тип</comment>
    <comment xml:lang="cs">Neznámý</comment>
    <comment xml:lang="da">ukendt</comment>
    <comment xml:lang="de">unbekannt</comment>
    <comment xml:lang="el">αγνωστο</comment>
    <comment xml:lang="eo">nekonata</comment>
    <comment xml:lang="es">desconocido</comment>
    <comment xml:lang="eu">ezezaguna</comment>
    <comment xml:lang="fi">tuntematon</comment>
    <comment xml:lang="fr">inconnu</comment>
    <comment xml:lang="hu">ismeretlen</comment>
    <comment xml:lang="it">sconosciuto</comment>
    <comment xml:lang="ja">不明</comment>
    <comment xml:lang="ko">알 수 없음</comment>
    <comment xml:lang="ms">Entah</comment>
    <comment xml:lang="nb">ukjent</comment>
    <comment xml:lang="nl">onbekend</comment>
    <comment xml:lang="nn">ukjend</comment>
    <comment xml:lang="no">ukjent</comment>
    <comment xml:lang="pl">nieznany typ</comment>
    <comment xml:lang="pt">desconhecido</comment>
    <comment xml:lang="pt_BR">Desconhecido</comment>
    <comment xml:lang="ru">неизвестный</comment>
    <comment xml:lang="rw">itazwi</comment>
    <comment xml:lang="sq">nuk njihet</comment>
    <comment xml:lang="sr">непознато</comment>
    <comment xml:lang="sv">okänd</comment>
    <comment xml:lang="uk">невідомо</comment>
    <comment xml:lang="zh_CN">未知</comment>
    <comment xml:lang="zh_TW">不明</comment>
    <magic priority="50">
      <match value="\037\036" type="string" offset="0"/>
      <match value="017437" type="host16" offset="0"/>
      <match value="0x1fff" type="host16" offset="0"/>
      <match value="\377\037" type="string" offset="0"/>
      <match value="0145405" type="host16" offset="0"/>
    </magic>
    <glob pattern="*.bin"/>
  </mime-type>
  <mime-type type="application/oda">
    <comment>ODA document</comment>
    <comment xml:lang="az">ODA sənədi</comment>
    <comment xml:lang="bg">Документ, формат ODA</comment>
    <comment xml:lang="cs">Dokument ODA</comment>
    <comment xml:lang="cy">Dogfen ODA</comment>
    <comment xml:lang="da">ODA-dokument</comment>
    <comment xml:lang="de">ODA-Dokument</comment>
    <comment xml:lang="el">έγγραφο ODA</comment>
    <comment xml:lang="eo">ODA-dokumento</comment>
    <comment xml:lang="es">Documento ODA</comment>
    <comment xml:lang="eu">ODA dokumentua</comment>
    <comment xml:lang="fi">ODA-asiakirja</comment>
    <comment xml:lang="fr">document ODA</comment>
    <comment xml:lang="hu">ODA-dokumentum</comment>
    <comment xml:lang="it">Documento ODA</comment>
    <comment xml:lang="ja">ODA ドキュメント</comment>
    <comment xml:lang="ko">ODA 문서</comment>
    <comment xml:lang="ms">Dokumen ODA</comment>
    <comment xml:lang="nb">ODA-dokument</comment>
    <comment xml:lang="nl">ODA-document</comment>
    <comment xml:lang="nn">ODA-dokument</comment>
    <comment xml:lang="no">ODA-dokument</comment>
    <comment xml:lang="pl">Dokument ODA</comment>
    <comment xml:lang="pt">documento ODA</comment>
    <comment xml:lang="pt_BR">Documento ODA</comment>
    <comment xml:lang="ru">документ ODA</comment>
    <comment xml:lang="sq">Dokument ODA</comment>
    <comment xml:lang="sr">ODA документ</comment>
    <comment xml:lang="sv">ODA-dokument</comment>
    <comment xml:lang="uk">Документ ODA</comment>
    <comment xml:lang="zh_CN">ODA 文档</comment>
    <comment xml:lang="zh_TW">ODA 文件</comment>
    <glob pattern="*.oda"/>
  </mime-type>
  <mime-type type="application/pdf">
    <comment>PDF document</comment>
    <comment xml:lang="bg">Документ, формат PDF</comment>
    <comment xml:lang="cs">Dokument PDF</comment>
    <comment xml:lang="cy">Dogfen PDF</comment>
    <comment xml:lang="da">PDF-dokument</comment>
    <comment xml:lang="de">PDF-Dokument</comment>
    <comment xml:lang="el">έγγραφο PDF</comment>
    <comment xml:lang="eo">PDF-dokumento</comment>
    <comment xml:lang="es">Documento PDF</comment>
    <comment xml:lang="eu">PDF dokumentua</comment>
    <comment xml:lang="fi">PDF-asiakirja</comment>
    <comment xml:lang="fr">document PDF</comment>
    <comment xml:lang="hu">PDF-dokumentum</comment>
    <comment xml:lang="it">Documento PDF</comment>
    <comment xml:lang="ja">PDF ドキュメント</comment>
    <comment xml:lang="ko">PDF 문서</comment>
    <comment xml:lang="ms">Dokumen PDF</comment>
    <comment xml:lang="nb">PDF-dokument</comment>
    <comment xml:lang="nl">PDF-document</comment>
    <comment xml:lang="nn">PDF-dokument</comment>
    <comment xml:lang="no">PDF-dokument</comment>
    <comment xml:lang="pl">Dokument PDF</comment>
    <comment xml:lang="pt">documento PDF</comment>
    <comment xml:lang="pt_BR">Documento PDF</comment>
    <comment xml:lang="ru">документ PDF</comment>
    <comment xml:lang="sq">Dokument PDF</comment>
    <comment xml:lang="sr">PDF документ</comment>
    <comment xml:lang="sv">PDF-dokument</comment>
    <comment xml:lang="uk">Документ PDF</comment>
    <comment xml:lang="zh_CN">PDF 文档</comment>
    <comment xml:lang="zh_TW">PDF 文件</comment>
    <magic priority="50">
      <match value="%PDF-" type="string" offset="0"/>
    </magic>
    <glob pattern="*.pdf"/>
    <alias type="application/x-pdf"/>
  </mime-type>
  <mime-type type="application/pgp">
    <comment>PGP message</comment>
    <comment xml:lang="az">PGP ismarışı</comment>
    <comment xml:lang="bg">Съобщение, формат PGP</comment>
    <comment xml:lang="cs">Zpráva PGP</comment>
    <comment xml:lang="cy">Neges PGP</comment>
    <comment xml:lang="da">PGP-meddelelse</comment>
    <comment xml:lang="de">PGP-Nachricht</comment>
    <comment xml:lang="el">μήνυμα PGP</comment>
    <comment xml:lang="eo">PGP-mesaĝo</comment>
    <comment xml:lang="es">Mensaje PGP</comment>
    <comment xml:lang="eu">PGP mezua</comment>
    <comment xml:lang="fi">PGP-viesti</comment>
    <comment xml:lang="fr">message PGP</comment>
    <comment xml:lang="hu">PGP-üzenet</comment>
    <comment xml:lang="it">Messaggio PGP</comment>
    <comment xml:lang="ja">PGP メッセージ</comment>
    <comment xml:lang="ko">PGP 메세지</comment>
    <comment xml:lang="ms">Mesej PGP</comment>
    <comment xml:lang="nb">PGP-melding</comment>
    <comment xml:lang="nl">PGP-bericht</comment>
    <comment xml:lang="nn">PGP-melding</comment>
    <comment xml:lang="no">PGP-melding</comment>
    <comment xml:lang="pl">Wiadomość PGP</comment>
    <comment xml:lang="pt">mensagem PGP</comment>
    <comment xml:lang="pt_BR">Mensagem PGP</comment>
    <comment xml:lang="ru">сообщение PGP</comment>
    <comment xml:lang="sq">Mesazh PGP</comment>
    <comment xml:lang="sr">PGP порука</comment>
    <comment xml:lang="sv">PGP-meddelande</comment>
    <comment xml:lang="uk">Повідомлення PGP</comment>
    <comment xml:lang="zh_CN">PGP 信件</comment>
    <comment xml:lang="zh_TW">PGP 訊息</comment>
    <glob pattern="*.pgp"/>
  </mime-type>
  <mime-type type="application/pgp-encrypted">
    <comment>PGP/MIME-encrypted message header</comment>
    <comment xml:lang="bg">Заглавна част на шифровано съобщение, формат PGP/MIME</comment>
    <comment xml:lang="cs">Hlavička zašifrované zprávy PGP/MIME</comment>
    <comment xml:lang="da">PGP/MIME-krypteret meddelelseshoved</comment>
    <comment xml:lang="de">PGP/MIME-verschlüsselter Nachrichtenkopf</comment>
    <comment xml:lang="el">κεφαλίδα μηνύματος κρυπτογραφημένου κατά PGP/MIME</comment>
    <comment xml:lang="eo">PGP/MIME-ĉifrita ĉapo de mesaĝo</comment>
    <comment xml:lang="es">Cabecera de mensaje cifrado PGP/MIME</comment>
    <comment xml:lang="eu">PGP/MIME enkriptatutako mezu-goiburua</comment>
    <comment xml:lang="fi">PGP/MIME-salattu viestiotsikko</comment>
    <comment xml:lang="fr">en-têtemessage PGP/MIME-encryptée</comment>
    <comment xml:lang="hu">PGP/MIME titkosított üzenetfejléc</comment>
    <comment xml:lang="ja">PGP/MIME 暗号化メッセージヘッダー</comment>
    <comment xml:lang="ko">PGP/MIME으로 암호화된 메세지 헤더</comment>
    <comment xml:lang="ms">Pengepala mesej terenkripsi PGP/MIME</comment>
    <comment xml:lang="nb">PGP/MIME-kryptert meldingshode</comment>
    <comment xml:lang="nl">PGP/MIME-gecodeerde berichtkop</comment>
    <comment xml:lang="nn">PGP/MIME-kryptert meldingshovud</comment>
    <comment xml:lang="no">PGP/MIME-kryptert meldingshode</comment>
    <comment xml:lang="pl">Nagłówek listu zaszyfrowanego PGP/MIME</comment>
    <comment xml:lang="pt">cabeçalho de mensagem cifrada com PGP/MIME</comment>
    <comment xml:lang="pt_BR">Cabeçalho de mensagem criptografada PGP/MIME</comment>
    <comment xml:lang="ru">заголовок зашифрованного сообщения PGP/MIME</comment>
    <comment xml:lang="sq">Header mesazhi të kriptuar PGP/MIME</comment>
    <comment xml:lang="sr">ПГП/МИМЕ шифровано заглавље поруке</comment>
    <comment xml:lang="sv">PGP/MIME-krypterat meddelandehuvud</comment>
    <comment xml:lang="uk">Заголовок шифрованого PGP/MIME повідомлення</comment>
    <comment xml:lang="zh_CN">PGP/MIME 加密的信件头</comment>
    <comment xml:lang="zh_TW">PGP/MIME 加密訊息標頭</comment>
  </mime-type>
  <mime-type type="application/pgp-keys">
    <comment>PGP keys</comment>
    <comment xml:lang="az">PGP açarları</comment>
    <comment xml:lang="bg">Ключове, формат PGP</comment>
    <comment xml:lang="cs">Klíče PGP</comment>
    <comment xml:lang="cy">Allweddi PGP</comment>
    <comment xml:lang="da">PGP-nøgler </comment>
    <comment xml:lang="de">PGP-Schlüssel</comment>
    <comment xml:lang="el">κλειδιά PGP</comment>
    <comment xml:lang="eo">PGP-ŝlosiloj</comment>
    <comment xml:lang="es">Claves PGP</comment>
    <comment xml:lang="eu">PGP giltzak</comment>
    <comment xml:lang="fi">PGP-avainrengas</comment>
    <comment xml:lang="fr">clés PGP</comment>
    <comment xml:lang="hu">PGP-kulcs</comment>
    <comment xml:lang="it">Chiavi PGP</comment>
    <comment xml:lang="ja">PGP 鍵</comment>
    <comment xml:lang="ko">PGP 키</comment>
    <comment xml:lang="ms">Kekunci PGP</comment>
    <comment xml:lang="nb">PGP-nøkler</comment>
    <comment xml:lang="nl">PGP-sleutels</comment>
    <comment xml:lang="nn">PGP-nøkler</comment>
    <comment xml:lang="no">PGP-nøkler</comment>
    <comment xml:lang="pl">Klucze PGP</comment>
    <comment xml:lang="pt">chaves PGP</comment>
    <comment xml:lang="pt_BR">Chaves PGP</comment>
    <comment xml:lang="ru">ключи PGP</comment>
    <comment xml:lang="sq">Kyçe PGP</comment>
    <comment xml:lang="sr">PGP кључ</comment>
    <comment xml:lang="sv">PGP-nycklar</comment>
    <comment xml:lang="uk">Ключі PGP</comment>
    <comment xml:lang="zh_CN">PGP 密钥</comment>
    <comment xml:lang="zh_TW">PGP 鑰匙</comment>
  </mime-type>
  <mime-type type="application/pgp-signature">
    <comment>detached OpenPGP signature</comment>
    <comment xml:lang="bg">Отделен подпис, формат OpenPGP</comment>
    <comment xml:lang="cs">Odpojený podpis OpenPGP</comment>
    <comment xml:lang="da">frigjort OpenPGP-signatur</comment>
    <comment xml:lang="de">isolierte OpenPGP-Signatur</comment>
    <comment xml:lang="el">αποκομμένη υπογραφή OpenPGP</comment>
    <comment xml:lang="eo">dekroĉa OpenPGP-subskribo</comment>
    <comment xml:lang="es">firma OpenPGP separada</comment>
    <comment xml:lang="eu">desuzturtako OpenPGP sinadura</comment>
    <comment xml:lang="fi">erillinen OpenPGP-allekirjoitus</comment>
    <comment xml:lang="fr">signature détachée OpenPGP</comment>
    <comment xml:lang="hu">leválasztott OpenPGP-aláírás</comment>
    <comment xml:lang="ja">分離 OpenPGP 署名</comment>
    <comment xml:lang="ko">떼어진 OpenPGP 서명</comment>
    <comment xml:lang="ms">Tandatangan OpenPGP terlerai</comment>
    <comment xml:lang="nb">frakoblet OpenPGP-signatur</comment>
    <comment xml:lang="nl">losse OpenPGP-ondertekening</comment>
    <comment xml:lang="nn">fråkopla OpenPGP-signatur</comment>
    <comment xml:lang="no">frakoblet OpenPGP-signatur</comment>
    <comment xml:lang="pl">oddzielony podpis OpenPGP</comment>
    <comment xml:lang="pt">assinatura OpenPGP solta</comment>
    <comment xml:lang="pt_BR">Assinatura OpenPGP destacada</comment>
    <comment xml:lang="ru">отсоединенная подпись OpenPGP</comment>
    <comment xml:lang="sq">firmë e palidhur OpenPGP</comment>
    <comment xml:lang="sr">одвојени ОпенПГП потпис</comment>
    <comment xml:lang="sv">frikopplad OpenPGP-signatur</comment>
    <comment xml:lang="uk">відокремлений OpenPGP підпис</comment>
    <comment xml:lang="zh_CN">分离的 OpenPGP 签名</comment>
  </mime-type>
  <mime-type type="application/pkcs7-mime">
    <comment>S/MIME file</comment>
    <comment xml:lang="az">S/MIME faylı</comment>
    <comment xml:lang="bg">Файл, формат S/MIME</comment>
    <comment xml:lang="cs">Soubor S/MIME</comment>
    <comment xml:lang="cy">Ffeil S/MIME</comment>
    <comment xml:lang="da">S/MIME-fil</comment>
    <comment xml:lang="de">S/MIME-Datei</comment>
    <comment xml:lang="el">αρχείο S/MIME</comment>
    <comment xml:lang="eo">S/MIME-dosiero</comment>
    <comment xml:lang="es">Fichero S/MIME</comment>
    <comment xml:lang="eu">S/MIME fitxategia</comment>
    <comment xml:lang="fi">S/MIME-tiedosto</comment>
    <comment xml:lang="fr">fichier S/MIME</comment>
    <comment xml:lang="hu">S/MIME-fájl</comment>
    <comment xml:lang="it">File S/MIME</comment>
    <comment xml:lang="ja">S/MIME ファイル</comment>
    <comment xml:lang="ko">S/MIME 파일</comment>
    <comment xml:lang="ms">Fail S/MIME</comment>
    <comment xml:lang="nb">S/MIME-fil</comment>
    <comment xml:lang="nl">S/MIME-bestand</comment>
    <comment xml:lang="nn">S/MIME-fil</comment>
    <comment xml:lang="no">S/MIME-fil</comment>
    <comment xml:lang="pl">Plik S/MIME</comment>
    <comment xml:lang="pt">ficheiro S/MIME</comment>
    <comment xml:lang="pt_BR">Arquivo S/MIME</comment>
    <comment xml:lang="sq">File S/MIME</comment>
    <comment xml:lang="sr">S/MIME датотека</comment>
    <comment xml:lang="sv">S/MIME-fil</comment>
    <comment xml:lang="uk">Файл S/MIME</comment>
    <comment xml:lang="zh_CN">S/MIME 文件</comment>
    <comment xml:lang="zh_TW">S/MIME 檔</comment>
  </mime-type>
  <mime-type type="application/pkcs7-signature">
    <comment>detached S/MIME signature</comment>
    <comment xml:lang="bg">Отделен подпис, формат S/MIME</comment>
    <comment xml:lang="cs">Odpojený podpis S/MIME</comment>
    <comment xml:lang="da">frigjort S/MIME-signatur</comment>
    <comment xml:lang="de">isolierte S/MIME-Signatur</comment>
    <comment xml:lang="el">αποκομμένη υπογραφή S/MIME</comment>
    <comment xml:lang="eo">dekroĉa S/MIME-subskribo</comment>
    <comment xml:lang="es">firma S/MIME separada</comment>
    <comment xml:lang="eu">desuzturtako S/MIME sinadura</comment>
    <comment xml:lang="fi">erillinen S/MIME-allekirjoitus</comment>
    <comment xml:lang="fr">signature détachée S/MIME</comment>
    <comment xml:lang="hu">leválasztott S/MIME-aláírás</comment>
    <comment xml:lang="ja">分離 S/MIME 署名</comment>
    <comment xml:lang="ko">떼어진 S/MIME 서명</comment>
    <comment xml:lang="ms">Tandatangan S/MIME terlerai</comment>
    <comment xml:lang="nb">frakoblet S/MIME-signatur</comment>
    <comment xml:lang="nl">losse S/MIME-ondertekening</comment>
    <comment xml:lang="nn">fråkopla S/MIME-signatur</comment>
    <comment xml:lang="no">frakoblet S/MIME-signatur</comment>
    <comment xml:lang="pl">oddzielony podpis S/MIME</comment>
    <comment xml:lang="pt">assinatura S/MIME solta</comment>
    <comment xml:lang="pt_BR">Assinatura S/MIME destacada</comment>
    <comment xml:lang="ru">отсоединенная подпись S/MIME</comment>
    <comment xml:lang="sq">firmë e palidhur S/MIME</comment>
    <comment xml:lang="sr">одвојени S/MIME потпис</comment>
    <comment xml:lang="sv">frikopplad S/MIME-signatur</comment>
    <comment xml:lang="uk">відокремлений S/MIME підпис</comment>
    <comment xml:lang="zh_CN">分离的 S/MIME 签名</comment>
    <glob pattern="*.p7s"/>
  </mime-type>
  <mime-type type="application/postscript">
    <comment>PostScript document</comment>
    <comment xml:lang="bg">Документ на PostScript</comment>
    <comment xml:lang="cs">Dokument PostScript</comment>
    <comment xml:lang="da">PostScript-dokument</comment>
    <comment xml:lang="de">PostScript-Dokument</comment>
    <comment xml:lang="el">έγγραφο PostScript</comment>
    <comment xml:lang="eo">PostScript-dokumento</comment>
    <comment xml:lang="es">Documento PostScript</comment>
    <comment xml:lang="eu">PostScript dokumentua</comment>
    <comment xml:lang="fi">PostScript-asiakirja</comment>
    <comment xml:lang="fr">document PostScript</comment>
    <comment xml:lang="hu">PostScript-dokumentum</comment>
    <comment xml:lang="it">Documento PostScript</comment>
    <comment xml:lang="ja">PostScript ドキュメント</comment>
    <comment xml:lang="ko">포스트스크립트 문서</comment>
    <comment xml:lang="ms">Dokumen PostScript</comment>
    <comment xml:lang="nb">PostScript-dokument</comment>
    <comment xml:lang="nl">PostScript-document</comment>
    <comment xml:lang="nn">PostScript-dokument</comment>
    <comment xml:lang="no">PostScript-dokument</comment>
    <comment xml:lang="pl">Dokument Postscript</comment>
    <comment xml:lang="pt">documento PostScript</comment>
    <comment xml:lang="pt_BR">Documento PostScript</comment>
    <comment xml:lang="ru">документ PostScript</comment>
    <comment xml:lang="sq">Dokument PostScript</comment>
    <comment xml:lang="sr">ПостСкрипт документ</comment>
    <comment xml:lang="sv">Postscript-dokument</comment>
    <comment xml:lang="uk">Документ PostScript</comment>
    <comment xml:lang="zh_CN">PostScript 文档</comment>
    <comment xml:lang="zh_TW">PostScript 文件</comment>
    <magic priority="50">
      <match value="\004%!" type="string" offset="0"/>
      <match value="%!" type="string" offset="0"/>
    </magic>
    <glob pattern="*.ps"/>
  </mime-type>
  <mime-type type="application/rtf">
    <sub-class-of type="text/plain"/>
    <comment>Rich Text Format</comment>
    <comment xml:lang="az">Zəngin Mətn Formatı</comment>
    <comment xml:lang="bg">Документ, формат Rich Text</comment>
    <comment xml:lang="cs">Rich Text Format</comment>
    <comment xml:lang="cy">Dogfen Testun Gyfoethog</comment>
    <comment xml:lang="da">Rigt tekst-dokument</comment>
    <comment xml:lang="de">Richt-Text-Format</comment>
    <comment xml:lang="el">έγγραφο Rich Text Format (RTF)</comment>
    <comment xml:lang="eo">Riĉa tekstformato</comment>
    <comment xml:lang="es">Formato de texto enriquecido</comment>
    <comment xml:lang="eu">Aberastutako testu formatua</comment>
    <comment xml:lang="fi">RTF-asiakirja</comment>
    <comment xml:lang="fr">Rich Text Format</comment>
    <comment xml:lang="hu">RTF-fájl</comment>
    <comment xml:lang="ja">リッチテキスト形式</comment>
    <comment xml:lang="ko">Rich Text 형식</comment>
    <comment xml:lang="ms">Dokumen Teks Kaya</comment>
    <comment xml:lang="nb">Rik tekst-format</comment>
    <comment xml:lang="nl">Rich Text Format-tekstdocument</comment>
    <comment xml:lang="nn">Rik tekst-dokument</comment>
    <comment xml:lang="no">Rik tekst-format</comment>
    <comment xml:lang="pl">Format rich text</comment>
    <comment xml:lang="pt">Formato de Texto Rico</comment>
    <comment xml:lang="pt_BR">Formato Rich Text</comment>
    <comment xml:lang="sq">Format Rich Text</comment>
    <comment xml:lang="sr">Обогаћени текстуални запис (RTF)</comment>
    <comment xml:lang="sv">Rikt textdokument</comment>
    <comment xml:lang="uk">Форматований текс (RTF)</comment>
    <comment xml:lang="zh_CN">RTF 丰富文本格式</comment>
    <comment xml:lang="zh_TW">RTF 文件</comment>
    <magic priority="50">
      <match value="{\\rtf" type="string" offset="0"/>
    </magic>
    <glob pattern="*.rtf"/>
  </mime-type>
  <mime-type type="application/smil">
    <sub-class-of type="text/plain"/>
    <comment>Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="az">Sinxronlaşdırılmış Multemediya İnteqrasiya Dili</comment>
    <comment xml:lang="bg">Файл за синхронизация на мултимедия, формат SMIL</comment>
    <comment xml:lang="cs">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="cy">Iaith Integreiddio Aml-Gyfrwng wedi ei Chydweddu</comment>
    <comment xml:lang="da">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="de">SMIL-Dokument</comment>
    <comment xml:lang="el">Γλώσσα Ενοποίησης Συγχρονισμένων Πολυμέσων (SMIL)</comment>
    <comment xml:lang="es">Lenguaje de integración de multimedia sincronizada (SMIL)</comment>
    <comment xml:lang="eu">Sinkronizatutako multimedia integraziorako lenguaia</comment>
    <comment xml:lang="fi">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="fr">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="hu">Szinkronizált multimédiaintegrációs nyelv</comment>
    <comment xml:lang="ja">同期マルチメディア統合言語 (SMIL)</comment>
    <comment xml:lang="ko">동기화 멀티미디어 통합 언어</comment>
    <comment xml:lang="ms">Bahasa Integrasi Multimedia Disegerak</comment>
    <comment xml:lang="nb">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="nl">Gesynchroniseerde multimedia integratietaal (SMIL)</comment>
    <comment xml:lang="nn">Synchronized Multimedia Integration Language</comment>
    <comment xml:lang="pl">Synchronizowany Multimedialny Język Integracyjny (SMIL)</comment>
    <comment xml:lang="pt">Linguagem de Integração Multimédia Sincronizada</comment>
    <comment xml:lang="pt_BR">Linguagem de Integração de Multimídia Sincronizada (SMIL)</comment>
    <comment xml:lang="sq">Gjuhë Synchronized Multimedia Integration</comment>
    <comment xml:lang="sr">Синхронизовани језик за интеграцију мултимедије (SMIL)</comment>
    <comment xml:lang="sv">Språk för synkroniserad multimediaintegration</comment>
    <comment xml:lang="uk">Інтеграційна мова синхронної мультимедія</comment>
    <glob pattern="*.smil"/>
    <glob pattern="*.smi"/>
    <glob pattern="*.sml"/>
  </mime-type>
  <mime-type type="application/stuffit">
    <comment>StuffIt archive</comment>
    <comment xml:lang="bg">Архив, формат StuffIt</comment>